version: '3.3'

services:

  app:
    image: ${IMAGE:-nov/main}
    links:
      - postgres
    environment:
      - POSTGRES_ENABLED=true
      - POSTGRES_SERVICE_URI=
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_SERVICE_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test